### ISSUE TITLE
Add global user support

### ISSUE THREAD

**Issue by lauraherzog** [conceptsandtraining/doil#100]
## Purpose

Running doil on a machine which are used by multiple users will cause several problems (this list is not complete):

* If a user creates an instance other users are not able to access this instance
* If a user adds a repository other users are not able to access this repository
* If a user wants to share their instance with other users there have to be several access rights problems which need to be solved by hand

## Solution

This issue will takle several todos accross the whole project and affects the configuration, group setup and folder structures of doil, its repositories, configurations and repositories. Following requirements are mandatory in order to implement a multi user support on shared systems:

* A user must be able to have their own repositories and instances which cannot be accessed by other users
* A user must be able to define a repository and instance as global so other users can access them
* A user must have an own configuration (~/.doil/config) which contents the user specific repositories and created instances
* A user must access a global configuration which contents repositories and instances marked as "shared"
* A user is only allowed to alter (update, delete) an instance, repository or pack created by themself and not marked as "shared"
* A user is only allowed to access log files of their own and global projects (must be own issue)

### Step 1: Refactor folder structure

Currently the folder structure of doil is not intuitive nor semanticly correct. Scripts, templates, repositories and other stuff are stored accross only the folders lib and tpl whereas lib contains the scripts and tpl everything else. The tpl folder especially containts servers, saltstacks, repositories and templates. In order to have a multiuser support we need to restructure the folders:

* `/usr/local/lib/doil/lib` - containts the scripts used by doil
* `/usr/local/lib/doil/server` - containts the proxy and salt server
* `/etc/doil/` - containts the shared configuration (see Step 3)
* `/usr/local/share/doil/templates` - containts templates which are needed to run an instance (currently only `minion`)
* `/usr/local/share/doil/stack` - containts the saltstack
* `/usr/local/share/doil/instances` - contains the shared instances configuration (symbolic links)
* `/usr/local/share/doil/repositories` - containts the repositories (see Step 4)

With that doil achieves to be more UNIX development standards.

### Step 2: Add a group `doil` and alter access rights

Installing doil will add a group `doil`. The access rights for the shared folders must be set accordingly (`root:doil`). Users must be added manually to the group with a hint in install script and readme.

If a user wants to use doil we need to introduce `doil system:user` with following commands which are only executeable as sudo user):

* `doil system:user add ${USER}`
* `doil system:user delete ${USER}`

This will create these user folders:

* `~/.doil/repositories/` - containts the user specific repositories
* `~/.doil/config/` - containts the user specific configurations
* `~/.doil/instances` - containts the user created instances configurations (symbolic links)

Also it adds or removes the user to or from the group `doil`

### Step 3: Add a shared configuration

There needs to be settings which are shared between the users. For the folder `/etc/doil` will be introduced which contains the file `doil.conf`, the folder `conf.d` and the folder `instances`.

#### `doil.conf`

This file contains every global configuration doil needs to know. As in #99 stated we need the host, and the default groupname of shared doil data which is both by default `doil`:

```
group = doil
host = doil
```

Don't forget to add explainations at these variables.

### Step 4: Move the currently installed configurations and repositories

If doil is already installed, we need to move all the currently installed data to their right place:

* `/usr/local/lib/doil/tpl/repos/` -> `/usr/local/share/doil/repositories`
* `~/.doil/config/repos` -> `/etc/doil/repositories.conf`

### Step 5: Alter Scripts to comply with above requirements and introduce `--global`

Every single script in doil needs to be edited to match the requirements. The flag `--global|-g` needs to be introduced to the arguments for following commands:

* `doil instances:create`
* `doil repo:add`
* `doil pack:import`

All the other scripts need a check if the command is available to the current user. If an instances, repo oder pack is not shared between the users, the user is not allowed to take action in:

**Instances**
* `doil instances:up`
* `doil instances:down`
* `doil instances:apply`
* `doil instances:cd`
* `doil instances:login`
* `doil instances:delete`

**Repository**
* `doil repo:update`
* `doil repo:remove` (which should be renamed to "delete" to match the semantics)

**Pack**
* `doil pack:export`
* `doil pack:import`

### Step 6: Differ from shared and local instances, repos and packs with the same name

If a user creates a local instance which has the same name as a global instance (or vise verca) doil needs to check within its commands if the user means their local instance or the shared one: Compare `doil instances:login ilias` with `doil instances:login ilias --global`. For that we need to introduce prefixes for each instance in their name. This will affect all instances, repo and pack commands of doil.

## TODO

* [x] Step 1: Refactor folder structure
* [x] Step 2: Add a group `doil` and alter access rights
* [x] Step 3: Add a shared configuration
* [ ] Step 4: Move the currently installed configurations and repositories
* [x] Step 5: Alter Scripts to comply with above requirements and introduce `--global`
* [x] Step 6: Differ from shared and local instances, repos and packs with the same name
